// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package store

import (
	"context"
	"time"

	"github.com/JoshBlazer/waybill/api/internal/money"
	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one

INSERT INTO idempotency_keys (principal, key, request_hash)
VALUES ($1, $2, $3)
ON CONFLICT (principal, key) DO NOTHING
RETURNING principal
`

type ClaimIdempotencyKeyParams struct {
	Principal   string
	Key         string
	RequestHash []byte
}

// Idempotency ----------------------------------------------------------------
// Inserts the key inside the caller's transaction. A concurrent request
// with the same key blocks here until the first transaction ends.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey, arg.Principal, arg.Key, arg.RequestHash)
	var principal string
	err := row.Scan(&principal)
	return principal, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET status_code = $1, response_body = $2, completed_at = now()
WHERE principal = $3 AND key = $4
`

type CompleteIdempotencyKeyParams struct {
	StatusCode   *int32
	ResponseBody []byte
	Principal    string
	Key          string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.StatusCode,
		arg.ResponseBody,
		arg.Principal,
		arg.Key,
	)
	return err
}

const getActiveAPIKey = `-- name: GetActiveAPIKey :one
SELECT k.contractor_id, k.secret_sha256
FROM api_keys k
WHERE k.prefix = $1 AND k.revoked_at IS NULL
`

type GetActiveAPIKeyRow struct {
	ContractorID uuid.UUID
	SecretSha256 []byte
}

func (q *Queries) GetActiveAPIKey(ctx context.Context, prefix string) (GetActiveAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKey, prefix)
	var i GetActiveAPIKeyRow
	err := row.Scan(&i.ContractorID, &i.SecretSha256)
	return i, err
}

const getChainCursor = `-- name: GetChainCursor :one
SELECT next_block FROM chain_cursors WHERE network = $1
`

func (q *Queries) GetChainCursor(ctx context.Context, network string) (int64, error) {
	row := q.db.QueryRow(ctx, getChainCursor, network)
	var next_block int64
	err := row.Scan(&next_block)
	return next_block, err
}

const getContractor = `-- name: GetContractor :one
SELECT id, legal_name, verified_at, created_at FROM contractors WHERE id = $1
`

func (q *Queries) GetContractor(ctx context.Context, id uuid.UUID) (Contractor, error) {
	row := q.db.QueryRow(ctx, getContractor, id)
	var i Contractor
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT principal, key, request_hash, status_code, response_body, created_at, completed_at FROM idempotency_keys WHERE principal = $1 AND key = $2
`

type GetIdempotencyRecordParams struct {
	Principal string
	Key       string
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord, arg.Principal, arg.Key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Principal,
		&i.Key,
		&i.RequestHash,
		&i.StatusCode,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getInvoiceByTrackingCode = `-- name: GetInvoiceByTrackingCode :one
SELECT i.id, i.contractor_id, i.tracking_code, i.description, i.asset_code, i.amount, i.payout_mode, i.state, i.expires_at, i.created_at, i.updated_at, c.legal_name AS contractor_name, c.verified_at AS contractor_verified_at
FROM invoices i JOIN contractors c ON c.id = i.contractor_id
WHERE i.tracking_code = $1
`

type GetInvoiceByTrackingCodeRow struct {
	ID                   uuid.UUID
	ContractorID         uuid.UUID
	TrackingCode         string
	Description          string
	AssetCode            string
	Amount               money.Amount
	PayoutMode           string
	State                string
	ExpiresAt            time.Time
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ContractorName       string
	ContractorVerifiedAt *time.Time
}

func (q *Queries) GetInvoiceByTrackingCode(ctx context.Context, trackingCode string) (GetInvoiceByTrackingCodeRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByTrackingCode, trackingCode)
	var i GetInvoiceByTrackingCodeRow
	err := row.Scan(
		&i.ID,
		&i.ContractorID,
		&i.TrackingCode,
		&i.Description,
		&i.AssetCode,
		&i.Amount,
		&i.PayoutMode,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractorName,
		&i.ContractorVerifiedAt,
	)
	return i, err
}

const getInvoiceForUpdate = `-- name: GetInvoiceForUpdate :one
SELECT id, contractor_id, tracking_code, description, asset_code, amount, payout_mode, state, expires_at, created_at, updated_at FROM invoices WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetInvoiceForUpdate(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceForUpdate, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ContractorID,
		&i.TrackingCode,
		&i.Description,
		&i.AssetCode,
		&i.Amount,
		&i.PayoutMode,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys (contractor_id, prefix, secret_sha256)
VALUES ($1, $2, $3)
ON CONFLICT (prefix) DO NOTHING
`

type InsertAPIKeyParams struct {
	ContractorID uuid.UUID
	Prefix       string
	SecretSha256 []byte
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey, arg.ContractorID, arg.Prefix, arg.SecretSha256)
	return err
}

const insertDepositAddress = `-- name: InsertDepositAddress :exec
INSERT INTO deposit_addresses (network, address, invoice_id, salt)
VALUES ($1, $2, $3, $4)
`

type InsertDepositAddressParams struct {
	Network   string
	Address   string
	InvoiceID uuid.UUID
	Salt      []byte
}

func (q *Queries) InsertDepositAddress(ctx context.Context, arg InsertDepositAddressParams) error {
	_, err := q.db.Exec(ctx, insertDepositAddress,
		arg.Network,
		arg.Address,
		arg.InvoiceID,
		arg.Salt,
	)
	return err
}

const insertInvoice = `-- name: InsertInvoice :one

INSERT INTO invoices (id, contractor_id, tracking_code, description, asset_code, amount, payout_mode, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, contractor_id, tracking_code, description, asset_code, amount, payout_mode, state, expires_at, created_at, updated_at
`

type InsertInvoiceParams struct {
	ID           uuid.UUID
	ContractorID uuid.UUID
	TrackingCode string
	Description  string
	AssetCode    string
	Amount       money.Amount
	PayoutMode   string
	ExpiresAt    time.Time
}

// Invoices ----------------------------------------------------------------
func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, insertInvoice,
		arg.ID,
		arg.ContractorID,
		arg.TrackingCode,
		arg.Description,
		arg.AssetCode,
		arg.Amount,
		arg.PayoutMode,
		arg.ExpiresAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.ContractorID,
		&i.TrackingCode,
		&i.Description,
		&i.AssetCode,
		&i.Amount,
		&i.PayoutMode,
		&i.State,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInvoiceEvent = `-- name: InsertInvoiceEvent :one
INSERT INTO invoice_events (invoice_id, type, from_state, to_state, data)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at
`

type InsertInvoiceEventParams struct {
	InvoiceID uuid.UUID
	Type      string
	FromState *string
	ToState   string
	Data      []byte
}

type InsertInvoiceEventRow struct {
	ID        int64
	CreatedAt time.Time
}

func (q *Queries) InsertInvoiceEvent(ctx context.Context, arg InsertInvoiceEventParams) (InsertInvoiceEventRow, error) {
	row := q.db.QueryRow(ctx, insertInvoiceEvent,
		arg.InvoiceID,
		arg.Type,
		arg.FromState,
		arg.ToState,
		arg.Data,
	)
	var i InsertInvoiceEventRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertPayment = `-- name: InsertPayment :one
INSERT INTO payments (network, tx_hash, log_index, block_number, block_hash, token_address,
                      from_address, to_address, invoice_id, asset_code, amount)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11)
ON CONFLICT (network, tx_hash, log_index) DO NOTHING
RETURNING id, network, tx_hash, log_index, block_number, block_hash, token_address, from_address, to_address, invoice_id, asset_code, amount, state, detected_at, confirmed_at, final_at
`

type InsertPaymentParams struct {
	Network      string
	TxHash       string
	LogIndex     int32
	BlockNumber  int64
	BlockHash    string
	TokenAddress string
	FromAddress  string
	ToAddress    string
	InvoiceID    uuid.UUID
	AssetCode    string
	Amount       money.Amount
}

// ON CONFLICT: the same log seen twice is the same payment (I9).
func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, insertPayment,
		arg.Network,
		arg.TxHash,
		arg.LogIndex,
		arg.BlockNumber,
		arg.BlockHash,
		arg.TokenAddress,
		arg.FromAddress,
		arg.ToAddress,
		arg.InvoiceID,
		arg.AssetCode,
		arg.Amount,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.TxHash,
		&i.LogIndex,
		&i.BlockNumber,
		&i.BlockHash,
		&i.TokenAddress,
		&i.FromAddress,
		&i.ToAddress,
		&i.InvoiceID,
		&i.AssetCode,
		&i.Amount,
		&i.State,
		&i.DetectedAt,
		&i.ConfirmedAt,
		&i.FinalAt,
	)
	return i, err
}

const latestInvoiceEventID = `-- name: LatestInvoiceEventID :one
SELECT coalesce(max(id), 0)::bigint FROM invoice_events WHERE invoice_id = $1
`

func (q *Queries) LatestInvoiceEventID(ctx context.Context, invoiceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, latestInvoiceEventID, invoiceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listChainTokens = `-- name: ListChainTokens :many
SELECT network, contract_address, asset_code FROM chain_tokens WHERE network = $1
`

func (q *Queries) ListChainTokens(ctx context.Context, network string) ([]ChainToken, error) {
	rows, err := q.db.Query(ctx, listChainTokens, network)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChainToken
	for rows.Next() {
		var i ChainToken
		if err := rows.Scan(&i.Network, &i.ContractAddress, &i.AssetCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepositAddresses = `-- name: ListDepositAddresses :many
SELECT network, address, invoice_id, salt FROM deposit_addresses WHERE invoice_id = $1 ORDER BY network
`

func (q *Queries) ListDepositAddresses(ctx context.Context, invoiceID uuid.UUID) ([]DepositAddress, error) {
	rows, err := q.db.Query(ctx, listDepositAddresses, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositAddress
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.Network,
			&i.Address,
			&i.InvoiceID,
			&i.Salt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceEvents = `-- name: ListInvoiceEvents :many
SELECT id, invoice_id, type, from_state, to_state, data, created_at FROM invoice_events WHERE invoice_id = $1 ORDER BY id
`

func (q *Queries) ListInvoiceEvents(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceEvent, error) {
	rows, err := q.db.Query(ctx, listInvoiceEvents, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceEvent
	for rows.Next() {
		var i InvoiceEvent
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Type,
			&i.FromState,
			&i.ToState,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenPayments = `-- name: ListOpenPayments :many
SELECT id, network, tx_hash, log_index, block_number, block_hash, token_address, from_address, to_address, invoice_id, asset_code, amount, state, detected_at, confirmed_at, final_at FROM payments WHERE network = $1 AND state IN ('detected', 'confirmed') ORDER BY block_number, log_index
`

func (q *Queries) ListOpenPayments(ctx context.Context, network string) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listOpenPayments, network)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.TxHash,
			&i.LogIndex,
			&i.BlockNumber,
			&i.BlockHash,
			&i.TokenAddress,
			&i.FromAddress,
			&i.ToAddress,
			&i.InvoiceID,
			&i.AssetCode,
			&i.Amount,
			&i.State,
			&i.DetectedAt,
			&i.ConfirmedAt,
			&i.FinalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatchedAddresses = `-- name: ListWatchedAddresses :many

SELECT address, invoice_id FROM deposit_addresses WHERE network = $1
`

type ListWatchedAddressesRow struct {
	Address   string
	InvoiceID uuid.UUID
}

// Payments (watcher) --------------------------------------------------------
// Every deposit address on a network, including expired invoices: late
// payments are still recorded (docs/RISKS.md §7).
func (q *Queries) ListWatchedAddresses(ctx context.Context, network string) ([]ListWatchedAddressesRow, error) {
	rows, err := q.db.Query(ctx, listWatchedAddresses, network)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWatchedAddressesRow
	for rows.Next() {
		var i ListWatchedAddressesRow
		if err := rows.Scan(&i.Address, &i.InvoiceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentConfirmed = `-- name: MarkPaymentConfirmed :exec
UPDATE payments SET state = 'confirmed', confirmed_at = now() WHERE id = $1 AND state = 'detected'
`

func (q *Queries) MarkPaymentConfirmed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentConfirmed, id)
	return err
}

const markPaymentFinal = `-- name: MarkPaymentFinal :exec
UPDATE payments SET state = 'final', final_at = now() WHERE id = $1 AND state = 'confirmed'
`

func (q *Queries) MarkPaymentFinal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentFinal, id)
	return err
}

const setChainCursor = `-- name: SetChainCursor :exec
INSERT INTO chain_cursors (network, next_block) VALUES ($1, $2)
ON CONFLICT (network) DO UPDATE SET next_block = EXCLUDED.next_block, updated_at = now()
`

type SetChainCursorParams struct {
	Network   string
	NextBlock int64
}

func (q *Queries) SetChainCursor(ctx context.Context, arg SetChainCursorParams) error {
	_, err := q.db.Exec(ctx, setChainCursor, arg.Network, arg.NextBlock)
	return err
}

const sumPaymentsByState = `-- name: SumPaymentsByState :one
SELECT coalesce(sum(amount), 0)::minor_units AS total
FROM payments
WHERE invoice_id = $1
  AND state = ANY($2::text[])
`

type SumPaymentsByStateParams struct {
	InvoiceID uuid.UUID
	States    []string
}

// Total of an invoice's payments that have reached at least the given state.
func (q *Queries) SumPaymentsByState(ctx context.Context, arg SumPaymentsByStateParams) (money.Amount, error) {
	row := q.db.QueryRow(ctx, sumPaymentsByState, arg.InvoiceID, arg.States)
	var total money.Amount
	err := row.Scan(&total)
	return total, err
}

const updateInvoiceState = `-- name: UpdateInvoiceState :exec
UPDATE invoices SET state = $1, updated_at = now() WHERE id = $2
`

type UpdateInvoiceStateParams struct {
	State string
	ID    uuid.UUID
}

func (q *Queries) UpdateInvoiceState(ctx context.Context, arg UpdateInvoiceStateParams) error {
	_, err := q.db.Exec(ctx, updateInvoiceState, arg.State, arg.ID)
	return err
}

const upsertChainToken = `-- name: UpsertChainToken :exec

INSERT INTO chain_tokens (network, contract_address, asset_code)
VALUES ($1, $2, $3)
ON CONFLICT (network, asset_code) DO UPDATE SET contract_address = EXCLUDED.contract_address
`

type UpsertChainTokenParams struct {
	Network         string
	ContractAddress string
	AssetCode       string
}

// Chain tokens -----------------------------------------------------------
func (q *Queries) UpsertChainToken(ctx context.Context, arg UpsertChainTokenParams) error {
	_, err := q.db.Exec(ctx, upsertChainToken, arg.Network, arg.ContractAddress, arg.AssetCode)
	return err
}

const upsertContractor = `-- name: UpsertContractor :one

INSERT INTO contractors (id, legal_name, verified_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET legal_name = EXCLUDED.legal_name, verified_at = EXCLUDED.verified_at
RETURNING id, legal_name, verified_at, created_at
`

type UpsertContractorParams struct {
	ID         uuid.UUID
	LegalName  string
	VerifiedAt *time.Time
}

// Contractors and API keys -----------------------------------------------
func (q *Queries) UpsertContractor(ctx context.Context, arg UpsertContractorParams) (Contractor, error) {
	row := q.db.QueryRow(ctx, upsertContractor, arg.ID, arg.LegalName, arg.VerifiedAt)
	var i Contractor
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.VerifiedAt,
		&i.CreatedAt,
	)
	return i, err
}
