// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package store

import (
	"context"

	"github.com/JoshBlazer/waybill/api/internal/money"
	"github.com/jackc/pgx/v5/pgtype"
)

const balanceCacheMismatches = `-- name: BalanceCacheMismatches :many
SELECT b.account_id, b.balance, coalesce(sum(p.amount), 0)::minor_units AS posted
FROM ledger_balances b
LEFT JOIN postings p ON p.account_id = b.account_id
GROUP BY b.account_id, b.balance
HAVING b.balance <> coalesce(sum(p.amount), 0)
`

type BalanceCacheMismatchesRow struct {
	AccountID int64
	Balance   money.Amount
	Posted    money.Amount
}

// Accounts whose cached balance differs from the sum of their postings.
// Must always return no rows.
func (q *Queries) BalanceCacheMismatches(ctx context.Context) ([]BalanceCacheMismatchesRow, error) {
	rows, err := q.db.Query(ctx, balanceCacheMismatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceCacheMismatchesRow
	for rows.Next() {
		var i BalanceCacheMismatchesRow
		if err := rows.Scan(&i.AccountID, &i.Balance, &i.Posted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, code, asset_code, kind, balance_rule FROM ledger_accounts WHERE code = $1
`

type GetAccountByCodeRow struct {
	ID          int64
	Code        string
	AssetCode   string
	Kind        string
	BalanceRule string
}

func (q *Queries) GetAccountByCode(ctx context.Context, code string) (GetAccountByCodeRow, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, code)
	var i GetAccountByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.AssetCode,
		&i.Kind,
		&i.BalanceRule,
	)
	return i, err
}

const getAccountsByIDs = `-- name: GetAccountsByIDs :many
SELECT id, code, asset_code, kind, balance_rule
FROM ledger_accounts WHERE id = ANY($1::bigint[]) ORDER BY id
`

type GetAccountsByIDsRow struct {
	ID          int64
	Code        string
	AssetCode   string
	Kind        string
	BalanceRule string
}

// Ordered by id: callers that lock accounts must always lock in this order.
func (q *Queries) GetAccountsByIDs(ctx context.Context, ids []int64) ([]GetAccountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getAccountsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountsByIDsRow
	for rows.Next() {
		var i GetAccountsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.AssetCode,
			&i.Kind,
			&i.BalanceRule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBalance = `-- name: GetBalance :one
SELECT balance FROM ledger_balances WHERE account_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, accountID int64) (money.Amount, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var balance money.Amount
	err := row.Scan(&balance)
	return balance, err
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, idempotency_key, kind, ref_type, ref_id, memo, reverses_entry_id, created_at
FROM journal_entries WHERE id = $1
`

type GetJournalEntryRow struct {
	ID              int64
	IdempotencyKey  string
	Kind            string
	RefType         string
	RefID           string
	Memo            string
	ReversesEntryID *int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetJournalEntry(ctx context.Context, id int64) (GetJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, id)
	var i GetJournalEntryRow
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.RefType,
		&i.RefID,
		&i.Memo,
		&i.ReversesEntryID,
		&i.CreatedAt,
	)
	return i, err
}

const getJournalEntryByIdempotencyKey = `-- name: GetJournalEntryByIdempotencyKey :one
SELECT id, idempotency_key, kind, ref_type, ref_id, memo, reverses_entry_id, created_at
FROM journal_entries WHERE idempotency_key = $1
`

type GetJournalEntryByIdempotencyKeyRow struct {
	ID              int64
	IdempotencyKey  string
	Kind            string
	RefType         string
	RefID           string
	Memo            string
	ReversesEntryID *int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) GetJournalEntryByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetJournalEntryByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getJournalEntryByIdempotencyKey, idempotencyKey)
	var i GetJournalEntryByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.RefType,
		&i.RefID,
		&i.Memo,
		&i.ReversesEntryID,
		&i.CreatedAt,
	)
	return i, err
}

const getReversalOf = `-- name: GetReversalOf :one
SELECT id FROM journal_entries WHERE reverses_entry_id = $1
`

func (q *Queries) GetReversalOf(ctx context.Context, entryID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, getReversalOf, entryID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAccount = `-- name: InsertAccount :one

INSERT INTO ledger_accounts (code, asset_code, kind, balance_rule)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO NOTHING
RETURNING id, code, asset_code, kind, balance_rule
`

type InsertAccountParams struct {
	Code        string
	AssetCode   string
	Kind        string
	BalanceRule string
}

type InsertAccountRow struct {
	ID          int64
	Code        string
	AssetCode   string
	Kind        string
	BalanceRule string
}

// Ledger queries. See docs/design/ledger.md.
// Creates an account, or returns the existing one with the same code. The
// caller compares the returned row with what it asked for.
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (InsertAccountRow, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.Code,
		arg.AssetCode,
		arg.Kind,
		arg.BalanceRule,
	)
	var i InsertAccountRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.AssetCode,
		&i.Kind,
		&i.BalanceRule,
	)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO journal_entries (idempotency_key, kind, ref_type, ref_id, memo, reverses_entry_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type InsertJournalEntryParams struct {
	IdempotencyKey  string
	Kind            string
	RefType         string
	RefID           string
	Memo            string
	ReversesEntryID *int64
}

type InsertJournalEntryRow struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (InsertJournalEntryRow, error) {
	row := q.db.QueryRow(ctx, insertJournalEntry,
		arg.IdempotencyKey,
		arg.Kind,
		arg.RefType,
		arg.RefID,
		arg.Memo,
		arg.ReversesEntryID,
	)
	var i InsertJournalEntryRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO postings (entry_id, account_id, asset_code, amount)
VALUES ($1, $2, $3, $4)
`

type InsertPostingParams struct {
	EntryID   int64
	AccountID int64
	AssetCode string
	Amount    money.Amount
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.Exec(ctx, insertPosting,
		arg.EntryID,
		arg.AccountID,
		arg.AssetCode,
		arg.Amount,
	)
	return err
}

const listPostingsByEntry = `-- name: ListPostingsByEntry :many
SELECT id, entry_id, account_id, asset_code, amount
FROM postings WHERE entry_id = $1 ORDER BY account_id, id
`

func (q *Queries) ListPostingsByEntry(ctx context.Context, entryID int64) ([]Posting, error) {
	rows, err := q.db.Query(ctx, listPostingsByEntry, entryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Posting
	for rows.Next() {
		var i Posting
		if err := rows.Scan(
			&i.ID,
			&i.EntryID,
			&i.AccountID,
			&i.AssetCode,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trialBalance = `-- name: TrialBalance :many
SELECT asset_code, sum(amount)::minor_units AS total FROM postings GROUP BY asset_code ORDER BY asset_code
`

type TrialBalanceRow struct {
	AssetCode string
	Total     money.Amount
}

// Sum of all postings per asset. Every row must be zero.
func (q *Queries) TrialBalance(ctx context.Context) ([]TrialBalanceRow, error) {
	rows, err := q.db.Query(ctx, trialBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrialBalanceRow
	for rows.Next() {
		var i TrialBalanceRow
		if err := rows.Scan(&i.AssetCode, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
