// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	// Confirms the database answers queries, not only that a connection opens.
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
